---
title: "Sydney Airbnb"
author: "Scott Onestak"
date: "March 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
if (!require(colorspace)) {install.packages("colorspace")}
if (!require(ggplot2)) {install.packages("ggplot2")}
if (!require(rgdal)) {install.packages("rgdal")}
if (!require(curl)) {install.packages("curl")}
if (!require(geojsonio)) {install.packages("geojsonio")}
if (!require(sp)) {install.packages("sp")}
if (!require(maps)) {install.packages("maps")}
if (!require(stringi)) {install.packages("stringi")}
if (!require(ggmap)) {install.packages("ggmap")}
if (!require(maptools)) {install.packages("maptools")}
if (!require(dplyr)) {install.packages("dplyr")}
if (!require(leaflet)) {install.packages("leaflet")}

library(colorspace)
library(ggplot2)
library(rgdal)
library(curl)
library(geojsonio)
library(sp)
library(maps)
library(stringi)
library(ggmap)
library(maptools)
library(dplyr)
library(leaflet)
library(devtools)
```


```{r read in data}
sydney = geojson_read("sydney-airbnb-open-data/neighbourhoods.geojson", what = "sp")
syd = fortify(sydney)
syd$id = as.numeric(syd$id)
neighbourhoods = as.data.frame(sydney@data$neighbourhood)
colnames(neighbourhoods) = "neighbourhood"
neighbourhoods$id = 0:37
syd = syd %>% left_join(.,neighbourhoods,by="id") %>% select(neighbourhood,id,piece,group,order,hole,lat,long)

sydneyairbnb = read.csv("sydney-airbnb.csv")
```

```{r overlay plot}
sydneyairbnbT = sydneyairbnb
colnames(sydneyairbnbT)[10:11] = c("lat","long")

coordinates(sydneyairbnbT)=~long+lat
class(sydneyairbnbT)
proj4string(sydneyairbnbT)=CRS("+proj=longlat +datum=NAD83")
sydneyairbnbT = spTransform(sydneyairbnbT,CRS(proj4string(sydney)))
identical(proj4string(sydneyairbnbT),proj4string(sydney))

sydneighborhoods = over(sydneyairbnbT,sydney)[,1]
sydneyairbnb$neighborhood2 = sydneighborhoods
```

```{r make map}
syd_map = ggplot(syd,aes(x=long,y=lat),col="black",fill=NA) +
  geom_polygon(color = 'black',size=1,aes(group=group),fill=NA) + 
    geom_point(data=sydneyairbnb,aes(x=longitude,y=latitude,col=sydneyairbnb$neighborhood2),size=.10) +
  coord_fixed(1.3) + ggtitle("Sydney Neighbourhoods") +
  theme(plot.title = element_text(hjust = 0.5),
            panel.background = element_blank(),
            axis.title = element_blank(),
            axis.line = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            legend.position = "none") 
syd_map
```

```{r descriptive statistics}
sydneyairbnb = sydneyairbnb[which(is.na(sydneyairbnb$neighborhood2) == F),]
AvgPrices = sydneyairbnb %>%
  group_by(neighborhood2,room_type) %>%
  summarise(Count = n(),
            PriceAvg = mean(price,na.rm=T),
            ReviewAvg = weighted.mean(overall_satisfaction,reviews,na.rm=T))
AvgPrices[AvgPrices == 'NaN'] = NA

MedianPrices = sydneyairbnb %>%
  group_by(neighborhood2,room_type) %>%
  summarise(PriceMed = median(price,na.rm=T),
            ReviewMed = median(overall_satisfaction,na.rm=T))
MedianPrices[MedianPrices == 'NaN'] = NA
Summary = AvgPrices %>% left_join(.,MedianPrices,by=c("neighborhood2","room_type"))
rm(AvgPrices,MedianPrices)

for(i in seq(from=1,to=dim(Summary)[1],by=1)){
  if(Summary[i,3] < 10){
    Summary[i,4] = NA
    Summary[i,5] = NA
    Summary[i,6] = NA
    Summary[i,7] = NA
  }
}

HomeApt = Summary %>% filter(room_type == "Entire home/apt")
colnames(HomeApt)[3:7] = c("Count_HomeApt","PriceAvg_HomeApt","ReviewAvg_HomeApt","PriceMed_HomeApt","ReviewMed_HomeApt")
HomeApt = HomeApt %>% select(-room_type)
PrivateRoom = Summary %>% filter(room_type == "Private room")
colnames(PrivateRoom)[3:7] = c("Count_PrivateRoom","PriceAvg_PrivateRoom","ReviewAvg_PrivateRoom","PriceMed_PrivateRoom","ReviewMed_PrivateRoom")
PrivateRoom = PrivateRoom %>% select(-room_type)

theStats = HomeApt %>% left_join(.,PrivateRoom,by="neighborhood2")
colnames(theStats)[1] = "neighbourhood"
rm(HomeApt,PrivateRoom)
syd = syd %>% left_join(.,theStats,by="neighbourhood")
```

```{r stats maps}
syd_priceavgHome = ggplot(syd,aes(x=long,y=lat,fill=PriceAvg_HomeApt),col="black") +
  geom_polygon(color = 'black',size=1,aes(group=group)) +
  coord_fixed(1.3) + ggtitle("Sydney Entire Home/Apt Average Price") +
  theme(plot.title = element_text(hjust = 0.5),
            panel.background = element_blank(),
            axis.title = element_blank(),
            axis.line = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            legend.position = "top") +
  guides(fill=guide_legend(title="Average Price"))
syd_priceavgHome

syd_pricemedHome = ggplot(syd,aes(x=long,y=lat,fill=PriceMed_HomeApt),col="black") +
  geom_polygon(color = 'black',size=1,aes(group=group)) +
  coord_fixed(1.3) + ggtitle("Sydney Entire Home/Apt Median Price") +
  theme(plot.title = element_text(hjust = 0.5),
            panel.background = element_blank(),
            axis.title = element_blank(),
            axis.line = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            legend.position = "top") +
  guides(fill=guide_legend(title="Median Price"))
syd_pricemedHome

syd_priceavgRoom = ggplot(syd,aes(x=long,y=lat,fill=PriceAvg_PrivateRoom),col="black") +
  geom_polygon(color = 'black',size=1,aes(group=group)) +
  coord_fixed(1.3) + ggtitle("Sydney Private Room Average Price") +
  theme(plot.title = element_text(hjust = 0.5),
            panel.background = element_blank(),
            axis.title = element_blank(),
            axis.line = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            legend.position = "top") +
  guides(fill=guide_legend(title="Average Price"))
syd_priceavgRoom

syd_pricemedRoom = ggplot(syd,aes(x=long,y=lat,fill=PriceMed_PrivateRoom),col="black") +
  geom_polygon(color = 'black',size=1,aes(group=group)) +
  coord_fixed(1.3) + ggtitle("Sydney Private Room Median Price") +
  theme(plot.title = element_text(hjust = 0.5),
            panel.background = element_blank(),
            axis.title = element_blank(),
            axis.line = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            legend.position = "top") +
  guides(fill=guide_legend(title="Median Price"))
syd_pricemedRoom
```




